---
- hosts: all
  become: yes
  tasks:
  - name: update packages & install apache2
    apt:
      name: apache2
      update_cache: yes
      state: present
  - name: restart apache after installation
    service:
      name: apache2
      enabled: yes
      state: restarted
  - name: php packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql
  - name: restart apache after php
    service:
      name: apache2
      enabled: yes
      state: restarted
      

