----
- hosts: all
  become: yes
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
  - name: start httpd
    service:
      name: httpd
      enabled: yes
      state: started
  - name: install php packages
    yum:
      name: "{{ items }}"
      state: present
    with_items:
      - php
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql
  - name: restart apache
    service:
      name: httpd
      state: restarted
      

